services:
  nginx-task:
    container_name: nginx-task
    image: nginx:1.24
    restart: no
    volumes:
      - .:/var/www/
      - ./.docker/config/nginx/:/etc/nginx/conf.d/
      - ./.docker/logs/nginx:/var/log/nginx/
    ports:
      - "80:80"
    networks:
      - web-network-task

  php-task:
    image: ${IMAGE}:${VERSION}
    build:
      context: ./.docker/
    container_name: php-task
    restart: no
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - web-network-task

  db-task:
    container_name: db-task
    image: postgres:17.2
    restart: no
    ports:
      - "5433:5432"
    environment:
        POSTGRES_DB: task
        POSTGRES_USER: task
        POSTGRES_PASSWORD: task
    security_opt:
      - seccomp:unconfined
    volumes:
      - database-task-bus:/var/lib/postgresql/data
    networks:
      - web-network-task

volumes:
    database-task-bus:
        name: database-task-bus

networks:
  web-network-task:
    name: web-network-task
    driver: bridge
